import {
  ArrowLeft,
  ArrowUp,
  ArrowUpNarrowWide,
  ArrowUpRight,
  Copy,
  Delete,
  Globe,
  Home,
  LayoutDashboardIcon,
  Lightbulb,
  Link,
  PenIcon,
  Plus,
  Settings,
  User,
  X,
} from "lucide-react";

export const ICONS = {
  home: <Home />,
  settings: <Settings />,
  dashboard: <LayoutDashboardIcon />,
  write: <PenIcon />,
  grow: <ArrowUpNarrowWide />,
  audience: <User />,
  view: <Globe />,
  electric: <Lightbulb/>,
  topArrow: <ArrowUp/>,
  copy: <Copy/>,
  link: <ArrowUpRight />,
  cross: <X />,
  delete: <Delete/>,
  plus: <Plus/>,
  backArrow: <ArrowLeft/>,
};
